listofstorageaccount:
  - name: beststorageaccountever1
    account_tier: Standard
    account_replication_type: GRS
    access_tier: Cool
    cross_tenant_replication_enabled: enabled
  - name: beststorageaccountever2
    account_tier: Standard
    account_replication_type: GRS
    access_tier: Cool
    cross_tenant_replication_enabled: enabled
