listofstorageaccount:
  - name: beststorageaccountever1    
    accoiunt_tier: Standard
    account_replication_type: GRS
    access _tier: Cool
    cross_tenant_replication_enabled: true
  - name: beststorageaccountever2    
    accoiunt_tier: Standard
    account_replication_type: GRS
    access _tier: Cool
    cross_tenant_replication_enabled: true
